// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MLApplicationsML.Model
{
    public class ModelInput
    {
        [ColumnName("Comment"), LoadColumn(0)]
        public string Comment { get; set; }


        [ColumnName("Label"), LoadColumn(1)]
        public string Label { get; set; }


    }
}
